### ISSUE TITLE
Напишите кто-нибудь план, а то мне лень

### ISSUE THREAD

**Issue by doojonio** [toshikFedotov/FanFile#1]
Чтоб ко вторнику (25.02.2020) фулл-план у был у меня на столе!

**Comment by ghost** [comment]
1. Продумывание требований проекта (5.03)
2. Разработка архитектуры проекта (19.03)
3. Схема базы данных (2.04)
4. Разработка бизнес-логики (16.04)
5. Создание API проекта (30.04)
6. Тестирование (14.05)

**Comment by doojonio** [comment]
Нормально

**Comment by LivingLeafFromTagil** [comment]
Да
